"""empty message

Revision ID: a84e00e9c850
Revises: 
Create Date: 2021-09-07 23:06:07.270724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84e00e9c850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Potions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('effect', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Wizards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bottles',
    sa.Column('w_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['Potions.id'], ),
    sa.ForeignKeyConstraint(['w_id'], ['Wizards.id'], ),
    sa.PrimaryKeyConstraint('w_id', 'p_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bottles')
    op.drop_table('Wizards')
    op.drop_table('Potions')
    # ### end Alembic commands ###
